<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>MSTest base classes for TestingKit integration tests.</Description>
    <IsTestProject>false</IsTestProject>
    <EnableMSTestRunner>false</EnableMSTestRunner>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../TestingKit/TestingKit.csproj" />
  </ItemGroup>

</Project>
