<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>RabbitMQ Testcontainers fixture.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Testcontainers.RabbitMq" />
    <PackageReference Include="RabbitMQ.Client" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../TestingKit/TestingKit.csproj" />
  </ItemGroup>

</Project>
