<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Azure Blob Storage (Azurite) Testcontainers fixture.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Testcontainers.Azurite" />
    <PackageReference Include="Azure.Storage.Blobs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../TestingKit/TestingKit.csproj" />
  </ItemGroup>

</Project>
